package com.greenlearner.product.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * @author - GreenLearner(https://www.youtube.com/c/greenlearner)
 */


@NoArgsConstructor
@AllArgsConstructor
@Data
@Document(collection = "product")
@ApiModel("Contains all the attributes required under product entity")
public class Product {

    @Id
    @ApiModelProperty("This is the unique Id of the product, will be generated by the system itself")
    private String id;

    @NotNull(message = "Product name should not be null")
    @ApiModelProperty("Name of the product")
    private String name;

    @NotNull(message = "Category of the product should not be null")
    private Category category;

    @Min(0)
    private double price;

    private String currency;

    @Max(100)
    @Min(0)
    private double discount;
    private String discountDescription;

    @ApiModelProperty("List of URL of the product images")
    private List<String> imageURLs;
}
